meta_product_name: "Discover Aventureiro"
meta_title: "Aventureiro - Experience the caiçara way"
meta_description: "Live an adventure in paradise, immerse in the wilderness, connect with nature and give it back to the caiçara community - in a sustainable and responsible way."
meta_image: "og-cover.png" # should exist in `app/assets/images/`
